### ISSUE TITLE
freezegun date is returned in a different container when using docker-compose

### ISSUE THREAD

**Issue by yuv-c** [spulec/freezegun#440]
I have a docker-compose.yml file with a few containers:
```
version: '3'
services:
  scan:
      container_name: scan
      build:
        context: ./
        dockerfile: Dockerfile
      command: "python3 scan.py"
      restart: always
...
...
  tests:
      build:
        context: ./
        dockerfile: Dockerfile
      command: "pytest -v --log-cli-level=DEBUG tests/tests.py"
```

I am using freezegun in my test container like so:
```
class TestClass(unittest.TestCase):
    def setUp(self) -> None:
      ....
    def test_something(self):
      with freeze_time("2021-11-09"):
         do_stuff...
```

When I `docker-compose up` the project, I get the following errors in the log:
```
scan          | 2022-01-27:16:28:40,500 INFO     [utils.py:242] Clearing redis session store
scan          | Traceback (most recent call last):
scan          |   File "/usr/mailing/scan.py", line 597, in <module>
scan          |     work()
scan          |   File "/usr/mailing/scan.py", line 566, in wrapper_decorator
scan          |     work_func()
scan          |   File "/usr/mailing/scan.py", line 589, in work
scan          |     if is_last_time_plus_delta_lt_now("last_monday_cleanup", MONDAY_CLEANUP_DELTA):
scan          |   File "/usr/mailing/scan.py", line 426, in is_last_time_plus_delta_lt_now
scan          |     datetime.strptime(get_last_time(last_time), "%Y-%m-%d %H:%M:%S.%f") + delta
scan          |   File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
scan          |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
scan          |   File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
scan          |     raise ValueError("time data %r does not match format %r" %
scan          | ValueError: time data '2021-11-09 00:00:00' does not match format '%Y-%m-%d %H:%M:%S.%f'
```
Notice that the date from the test container in the last row.
The test container runs as expected.

Is this a bug or a feature (I am seriously asking), and how can I avoid this?
